spring:
  application:
    name: ArticleService
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/articledb} #use this when running the app as a docker container.
    #url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/articledb}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-udith-nalaka.au.auth0.com/
          audiences: https//article-service-api


logging:
  level:
    org.springframework.web: WARN
    com.ud.article.articles: INFO

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true