spring:
  application:
    name: ClientOrderService
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    io.github.resilience4j.circuitbreaker: DEBUG


resilience4j: # resilience4j tuning for the application
  circuitbreaker:
    instances:
      orderService:
        register-health-indicator: true
        failure-rate-threshold: 50
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 50

  retry:
    instances:
      orderService:
        maxAttempts: 2
        waitDuration: 500ms

  timelimiter:
    instances:
      orderService:
        timeoutDuration: 3s

app:
  rest-client: # these config params are used when RestClient does an external call to another service.
    connect-timeout: 2s
    response-timeout: 5s
    connection-pool:
      max-total: 200
      max-per-route: 50
      idle-evict-timeout: 30s
    services:
      order-service:
        base-url: http://localhost:8080/orders/

